package es.appsandroidsite.quepues.modelo;
// Generated 26-abr-2016 13:44:46 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private String codigo;
     private int id;
     private String nombre;
     private Date ultimaMod;
     private Set<Opcion> opcions = new HashSet<Opcion>(0);
     private Set<Url> urls = new HashSet<Url>(0);

    public Categoria() {
    }

    public Categoria(String codigo) {
        this.codigo = codigo;
    }

	
    public Categoria(int id, Date ultimaMod) {
        this.id = id;
        this.ultimaMod = ultimaMod;
    }
    public Categoria(int id, String nombre, Date ultimaMod, Set<Opcion> opcions, Set<Url> urls) {
       this.id = id;
       this.nombre = nombre;
       this.ultimaMod = ultimaMod;
       this.opcions = opcions;
       this.urls = urls;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getUltimaMod() {
        return this.ultimaMod;
    }
    
    public void setUltimaMod(Date ultimaMod) {
        this.ultimaMod = ultimaMod;
    }
    public Set<Opcion> getOpcions() {
        return this.opcions;
    }
    
    public void setOpcions(Set<Opcion> opcions) {
        this.opcions = opcions;
    }
    public Set<Url> getUrls() {
        return this.urls;
    }
    
    public void setUrls(Set<Url> urls) {
        this.urls = urls;
    }




}


