package es.appsandroidsite.quepues.modelo;
// Generated 26-abr-2016 13:44:46 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Opcion generated by hbm2java
 */
public class Opcion  implements java.io.Serializable {


     private Integer id;
     private Categoria categoria;
     private Pregunta pregunta;
     private String texto;
     private Date ultimaMod;

    public Opcion() {
    }

	
    public Opcion(Date ultimaMod) {
        this.ultimaMod = ultimaMod;
    }
    public Opcion(Categoria categoria, Pregunta pregunta, String texto, Date ultimaMod) {
       this.categoria = categoria;
       this.pregunta = pregunta;
       this.texto = texto;
       this.ultimaMod = ultimaMod;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }
    public Date getUltimaMod() {
        return this.ultimaMod;
    }
    
    public void setUltimaMod(Date ultimaMod) {
        this.ultimaMod = ultimaMod;
    }




}


