package es.appsandroidsite.quepues.modelo;
// Generated 26-abr-2016 13:44:46 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pregunta generated by hbm2java
 */
public class Pregunta  implements java.io.Serializable {


     private Integer id;
     private Test test;
     private String texto;
     private Integer numero;
     private Date ultimaMod;
     private Set<Opcion> opcions = new HashSet<Opcion>(0);

    public Pregunta() {
    }

	
    public Pregunta(Date ultimaMod) {
        this.ultimaMod = ultimaMod;
    }
    public Pregunta(Test test, String texto, Integer numero, Date ultimaMod, Set<Opcion> opcions) {
       this.test = test;
       this.texto = texto;
       this.numero = numero;
       this.ultimaMod = ultimaMod;
       this.opcions = opcions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Test getTest() {
        return this.test;
    }
    
    public void setTest(Test test) {
        this.test = test;
    }
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public Date getUltimaMod() {
        return this.ultimaMod;
    }
    
    public void setUltimaMod(Date ultimaMod) {
        this.ultimaMod = ultimaMod;
    }
    public Set<Opcion> getOpcions() {
        return this.opcions;
    }
    
    public void setOpcions(Set<Opcion> opcions) {
        this.opcions = opcions;
    }




}


