package es.appsandroidsite.quepues.modelo;
// Generated 26-abr-2016 13:44:46 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Test generated by hbm2java
 */
public class Test  implements java.io.Serializable {


     private String codigo;
     private int id;
     private String tipo;
     private Date ultimaMod;
     private Set<Pregunta> preguntas = new HashSet<Pregunta>(0);
     private Set<Url> urls = new HashSet<Url>(0);

    public Test() {
    }

    public Test(String codigo) {
        this.codigo = codigo;
    }

    
	
    public Test(int id, Date ultimaMod) {
        this.id = id;
        this.ultimaMod = ultimaMod;
    }
    public Test(int id, String tipo, Date ultimaMod, Set<Pregunta> preguntas, Set<Url> urls) {
       this.id = id;
       this.tipo = tipo;
       this.ultimaMod = ultimaMod;
       this.preguntas = preguntas;
       this.urls = urls;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Date getUltimaMod() {
        return this.ultimaMod;
    }
    
    public void setUltimaMod(Date ultimaMod) {
        this.ultimaMod = ultimaMod;
    }
    public Set<Pregunta> getPreguntas() {
        return this.preguntas;
    }
    
    public void setPreguntas(Set<Pregunta> preguntas) {
        this.preguntas = preguntas;
    }
    public Set<Url> getUrls() {
        return this.urls;
    }
    
    public void setUrls(Set<Url> urls) {
        this.urls = urls;
    }




}


