package es.appsandroidsite.quepues.modelo;
// Generated 26-abr-2016 13:44:46 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Url generated by hbm2java
 */
public class Url  implements java.io.Serializable {


     private Integer id;
     private Categoria categoria;
     private Test test;
     private String subCategoria;
     private String url;
     private Date ultimaMod;

    public Url() {
    }

	
    public Url(Date ultimaMod) {
        this.ultimaMod = ultimaMod;
    }
    public Url(Categoria categoria, Test test, String subCategoria, String url, Date ultimaMod) {
       this.categoria = categoria;
       this.test = test;
       this.subCategoria = subCategoria;
       this.url = url;
       this.ultimaMod = ultimaMod;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Test getTest() {
        return this.test;
    }
    
    public void setTest(Test test) {
        this.test = test;
    }
    public String getSubCategoria() {
        return this.subCategoria;
    }
    
    public void setSubCategoria(String subCategoria) {
        this.subCategoria = subCategoria;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Date getUltimaMod() {
        return this.ultimaMod;
    }
    
    public void setUltimaMod(Date ultimaMod) {
        this.ultimaMod = ultimaMod;
    }




}


